- name: Install oh-my-zsh
  shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended --keep-zshrc

- name: Change shell to zsh
  become: yes
  user:
    name: hugh
    shell: /bin/zsh